-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS Y, MONTH(SALES_DATE) AS M, GENDER, COUNT(DISTINCT(USER_ID))
FROM USER_INFO I JOIN ONLINE_SALE S
	USING (USER_ID)
WHERE GENDER IS NOT NULL
GROUP BY Y, M, GENDER
ORDER BY Y, M, GENDER