-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, PRICE * SUM(AMOUNT) AS TOTAL
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O
	USING (PRODUCT_ID)
WHERE MONTH(PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID
ORDER BY TOTAL DESC, PRODUCT_ID