-- 코드를 입력하세요
SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS AVERAGE
FROM REST_REVIEW R JOIN REST_INFO I
	USING (REST_ID)
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY AVERAGE DESC, FAVORITES DESC
